server:
  port: 8090
spring:
  application:
    name: contacts
  profiles:
    active: "WebFlux"
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgrespw
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/db.changelog-master.xml
    enabled: true